- name: deploying frontend by playbook
  hosts: all
  become: yes
  tasks: 
    - name: disable the nginx
      ansible.builtin.shell: dnf module disable nginx -y

    - name: enable 1.24 nginx version
      ansible.builtin.shell: dnf module enable nginx:1.24 -y

  #  - name: install nginx 1.24 version
  #    ansible.builtin.shell: dnf install nginx -y

    - name: install nginx
      ansible.builtin.dnf: 
        name: nginx
        state: present
          
    - name: copy nginx.conf
      ansible.builtin.template: 
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: start nginx service
      ansible.builtin.systemd_service: 
        name: nginx
        state: started
        enabled: yes

